### ISSUE TITLE
Progress update

### ISSUE THREAD

**Issue by tkimva** [tkimva/dark_silicon#3]
Hi Dr. Tan,
My update keeping growing and wordy, so it's better to directly see the following dynamic page. 
Please see today's update.
Please keep watching the following page instead of the daily email. 
If I have significant update in this project then I will send you the email instead.

https://github.com/tkimva/dark_silicon

I also hope to finish this soon
Thanks,

**Comment by sheldonucr** [comment]
Sure, I will take a look at it soon.

-Sheldon
On Mar 26, 2015, at 12:04 AM, Taeyoung Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dr. Tan,
My update keeping growing and wordy, so it's better to directly see the following dynamic page.
Please see today's update.
Please keep watching the following page instead of the daily email.
If I have significant update in this project then I will send you the email instead.

https://github.com/tkimva/dark_silicon

I also hope to finish this soon
Thanks,

**Comment by sheldonucr** [comment]
Taeyoung,

What is sniper program. it is a wrapper function to interface McPat to support DVFS?
Your plan seems quite aggressive.

How about the tcad paper?

-Sheldon

Sniper Multi-Core Simulator


On Mar 26, 2015, at 12:04 AM, Taeyoung Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dr. Tan,
My update keeping growing and wordy, so it's better to directly see the following dynamic page.
Please see today's update.
Please keep watching the following page instead of the daily email.
If I have significant update in this project then I will send you the email instead.

https://github.com/tkimva/dark_silicon

I also hope to finish this soon
Thanks,

**Comment by tkimva** [comment]
McPat is multithreaded and multicore power and size simulator by HPLabs.

Sniper is bigger project and more accurate x86 multicore model by Intel which including McPat inside. It support basic McPat function and the following more functions

- Intel's interval core model
- DVFS support
- Heterogeneous support

My major job will be modifying DVFS with darksilicon and adding plugin our EM-aware Reliability function inside Sniper then we can do lots of experiements for manycore and dark silicon.

For TCAD, you meant the work with Prof Zhu's group?
As you know, it has been hodling due to this work, once this work done, I will do cplex programming and will do experiment.
